### ISSUE TITLE
Gain scaling

### ISSUE THREAD

**Issue by cmsavage** [sparkfun/APDS-9301_Breakout#2]
After reading light levels from multiple APDS-9301 boards using this library, I have found that the values returned by `APDS9301::readLuxLevel()` are at least an order of magnitude lower than expected and as measured from a phone app (though such measurements are [not expected to be terribly accurate](https://www.dial.de/en/blog/article/luxmeter-app-versus-measuring-deviceare-smartphones-suitable-for-measuring-illuminance/)).  Still, I found this library differs from how the [TSL2561 library](https://github.com/sparkfun/SparkFun_TSL2561_Arduino_Library) treats the empirical formula for lux found in the [APDS-9301 data sheet](https://cdn.sparkfun.com/assets/3/2/c/0/8/AV02-2315EN0.pdf).  This library assumes that formula applies to the low gain readings, while the latter assumes it applies to the high gain readings (see [here](https://github.com/sparkfun/SparkFun_TSL2561_Arduino_Library/blob/827ec2831706ae7cf1d63d30cc90fc6844a96369/src/SparkFunTSL2561.cpp#L216)); the data sheet itself is ambiguous as to the gain to be used in that formula.

The end result is that the two libraries give lux values different by a factor of 16.  Given my comparison with other sensors, I suspect the scaling in this library is incorrect.  A fix would be to replace:
```java
  if (getGain() == HIGH_GAIN)
  {
    ch0 /= 16;
    ch1 /= 16;
  }
```
with:
```java
  if (getGain() == LOW_GAIN) 
  {
    ch0 *= 16;
    ch1 *= 16;
  }
```
Can anyone confirm a scaling issue and, if so, apply the fix?

**Comment by cmsavage** [comment]
I got my hands on a lux meter and the APDS-9301 gives results accurate within 10-20% if the `readLuxLevel()` value is multiplied by 16.  This library does seem to be applying the empirical formula at the wrong gain.

**Comment by mhord** [comment]
Please give it a try now. I've updated the library with the change you suggested.

**Comment by cmsavage** [comment]
The lux values are now consistent with a lux meter.  Thanks!

**Comment by mhord** [comment]
Thanks for the feedback! We appreciate it!
